### ISSUE TITLE
Save settings after close

### ISSUE THREAD

**Issue by calhix** [riscygeek/billig-sweeper#1]
I love this app! It's the only minesweeper from what I can tell that works great on the Pinephone. Would you be able to have it save the settings from the previous session (such as amount of mines and length/width). It's just a little cumbersome to make the changes each time.

**Comment by riscygeek** [comment]
Done, are you able to test it?

**Comment by calhix** [comment]
I just have my pinephone currently so unable to test (just using flatpak) but I'm grateful for working on it so fast!

**Comment by riscygeek** [comment]
Ok, nevermind. I'm gonna try before the next release.

**Comment by riscygeek** [comment]
The beta version is out on flathub-beta. The official release (v1.2.1) will be available in 2h estimated on regular flathub.
