### ISSUE TITLE
Change background color

### ISSUE THREAD

**Issue by calhix** [riscygeek/billig-sweeper#3]
Purple I think is slightly jarring, I think it would be preferable for it to be black or near black/very dark grey.

**Comment by riscygeek** [comment]
The background color can now be changed in the config.
Do you have a suggested color code for the default color?

**Comment by calhix** [comment]
Awesome thanks! How about #0f0f0f?

**Comment by riscygeek** [comment]
Yeah, looks ok for me.

**Comment by calhix** [comment]
Would it be possible to just fill the screen with the minefield?

**Comment by riscygeek** [comment]
Not really, due to how I made it. It would mean that the minefield would be stretched in a direction if the screen is not 1:1.

**Comment by riscygeek** [comment]
At least without scaling, but I'm working on that one as we speak.
