### ISSUE TITLE
Track time stats

### ISSUE THREAD

**Issue by calhix** [riscygeek/billig-sweeper#8]
It would be a nice to be able to track stats for completion times for each configuration but keep the timer invisible (perhaps you could add a flag to make it visible for desktop users) so you can ensure max field size.

**Comment by riscygeek** [comment]
Great idea. I think incorporating it into the "Game over" "You win!" screens would be a good idea.

**Comment by riscygeek** [comment]
Done, it looks ugly, but it works.
